[package]
name = "Phantasma-Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.17"
tokio = { version = "1.28.1", features = ["full"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
byteorder = "1.4.3"
num-bigint = "0.4.3"
base58 = "0.2.0"
secp256k1 = "0.27.0"
ed25519-dalek = "1.0.1"
rand = "0.8.3"